#!/usr/bin/env node

const app = require('../app')
const port = normalizePort(process.env.PORT || '3000')

app.listen(process.env.PORT || config.port, () => console.log(`Radarprice app listening on port ${process.env.PORT || config.port}!`))
